### ISSUE TITLE
when I use this twice,some problem occurs.

### ISSUE THREAD

**Issue by leizhiyuan** [kostaskougios/cloning#42]
I use this in my eclipse plugin.

First. I cloned rightly,but When I open my eclipse plugin, and clone again,It set wrong value to the property of the object. just like 

java.lang.IllegalArgumentException: Can not set java.lang.String field  A field propertyName to B 

A is my object,B is another  property of A, but not the current property 

is there some caches?

**Comment by kostaskougios** [comment]
There is a reflection cache for class fields:

     private final ConcurrentHashMap<Class<?>, List<Field>> fieldsCache 
= new ConcurrentHashMap<Class<?>, List<Field>>();

This is per Cloner instance, so it shouldn't be a problem if you 
re-instantiate the Cloner when your eclipse plugin reloads.

How do you instantiate Cloner and where do you keep the instance?

**Comment by leizhiyuan** [comment]
@kostaskougios  thanks for your reply,I debugged it again.

Cloner.java ,(1.9.2)

```java

final boolean shouldClone = (cloneSynthetics || (!cloneSynthetics && !field.isSynthetic())) && (cloneAnonymousParent || ((!cloneAnonymousParent && !isAnonymousParent(field))));
final Object fieldObjectClone = clones != null ? (shouldClone ? cloneInternal(fieldObject, clones) : fieldObject) : fieldObject;
field.set(newInstance, fieldObjectClone);
```
in line 453, the value of fieldObjectClone is right,it is excepted value,

when execute field.set(newInstance, fieldObjectClone);,it throws this Exception,

```java
java.lang.IllegalArgumentException: Can not set java.lang.String field MyClass.invokeId to MyClass
	at sun.reflect.UnsafeFieldAccessorImpl.throwSetIllegalArgumentException(UnsafeFieldAccessorImpl.java:164)
	at sun.reflect.UnsafeFieldAccessorImpl.throwSetIllegalArgumentException(UnsafeFieldAccessorImpl.java:168)
	at sun.reflect.UnsafeFieldAccessorImpl.ensureObj(UnsafeFieldAccessorImpl.java:55)
	at sun.reflect.UnsafeObjectFieldAccessorImpl.set(UnsafeObjectFieldAccessorImpl.java:75)
```

so weird... first is ok,and second is wrong, I will debug again and make it clear. if you have some idea?

**Comment by leizhiyuan** [comment]
update

I debugged 

```java
field.set(newInstance, fieldObjectClone);
```

and 

```java
 public void set(Object obj, Object value)
        throws IllegalArgumentException, IllegalAccessException
    {
        ensureObj(obj);
        if (isFinal) {
            throwFinalFieldIllegalAccessException(value);
        }
        if (value != null) {
            if (!field.getType().isAssignableFrom(value.getClass())) {
                throwSetIllegalArgumentException(value);
            }
        }
        unsafe.putObject(obj, fieldOffset, value);
    }
```

in  ensureObj(obj);

```java
 protected void ensureObj(Object o) {
        // NOTE: will throw NullPointerException, as specified, if o is null
        if (!field.getDeclaringClass().isAssignableFrom(o.getClass())) {
            throwSetIllegalArgumentException(o);
        }
    }
```

It throws this exception. maybe Classloader occurs this problem?

**Comment by kostaskougios** [comment]
On 28/10/15 10:50, Lei Zhiyuan wrote:
>
> @kostaskougios <https://github.com/kostaskougios> thanks for your 
> reply,I debugged it again.
>
> Cloner.java ,(1.9.2)
>
> final  boolean  shouldClone=  (cloneSynthetics||  (!cloneSynthetics&&  !field.isSynthetic()))&&  (cloneAnonymousParent||  ((!cloneAnonymousParent&&  !isAnonymousParent(field))));
> final  Object  fieldObjectClone=  clones!=  null  ?  (shouldClone?  cloneInternal(fieldObject, clones):  fieldObject):  fieldObject;
> field.set(newInstance, fieldObjectClone);
what is the value of newInstance, fieldObjectClone?

It might be a classloader issue as eclipse uses a different classloader 
for each plugin. So the cloned values might be from a different 
classloader => incompatible.

Also how do you instantiate cloner? Try Cloner.shared()

**Comment by leizhiyuan** [comment]
Thank you so much.

I tried `Cloner.shared()` and change my code to create a new  Cloner object every time to ensure,It works, I will try to understand  the difference between these usages.

 you create a very excellent library, Thank you so much. :)
