### ISSUE TITLE
NoClassDefFoundError 

### ISSUE THREAD

**Issue by djdance** [kostaskougios/cloning#59]
> java.lang.NoClassDefFoundError: Failed resolution of: Lorg/objenesis/ObjenesisStd;
>                                                                  at com.rits.cloning.ObjenesisInstantiationStrategy.<init>(ObjenesisInstantiationStrategy.java:13)
>                                                                  at com.rits.cloning.ObjenesisInstantiationStrategy.<clinit>(ObjenesisInstantiationStrategy.java:20)
>                                                                  at com.rits.cloning.ObjenesisInstantiationStrategy.getInstance(ObjenesisInstantiationStrategy.java:24)
>                                                                  at com.rits.cloning.Cloner.<init>(Cloner.java:53)
>                                                                  at com.myproject.project.main$15.onClick(main.java:819)
>                                                                  at android.view.View.performClick(View.java:4848)
>                                                                  at android.view.View$PerformClick.run(View.java:20262)
>                                                                  at android.os.Handler.handleCallback(Handler.java:815)
>                                                                  at android.os.Handler.dispatchMessage(Handler.java:104)
>                                                                  at android.os.Looper.loop(Looper.java:194)
>                                                                  at android.app.ActivityThread.main(ActivityThread.java:5637)
>                                                                  at java.lang.reflect.Method.invoke(Native Method)
>                                                                  at java.lang.reflect.Method.invoke(Method.java:372)
>                                                                  at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:960)
>                                                                  at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:755)
>                                                               Caused by: java.lang.ClassNotFoundException: Didn't find class "org.objenesis.ObjenesisStd" on path: DexPathList[[zip file "/data/app/com.myproject.project-1/base.apk", zip file "/data/app/com.myproject.project-1/split_lib_dependencies_apk.apk", zip file "/data/app/com.myproject.project-1/split_lib_slice_0_apk.apk", zip file "/data/app/com.myproject.project-1/split_lib_slice_1_apk.apk", zip file "/data/app/com.myproject.project-1/split_lib_slice_2_apk.apk", zip file "/data/app/com.myproject.project-1/split_lib_slice_3_apk.apk", zip file "/data/app/com.myproject.project-1/split_lib_slice_4_apk.apk", zip file "/data/app/com.myproject.project-1/split_lib_slice_5_apk.apk", zip file "/data/app/com.myproject.project-1/split_lib_slice_6_apk.apk", zip file "/data/app/com.myproject.project-1/split_lib_slice_7_apk.apk", zip file "/data/app/com.myproject.project-1/split_lib_slice_8_apk.apk", zip file "/data/app/com.myproject.project-1/split_lib_slice_9_apk.apk"],nativeLibraryDirectories=[/vendor/lib, /system/lib]]
>                                                                  at dalvik.system.BaseDexClassLoader.findClass(BaseDexClassLoader.java:56)
>                                                                  at java.lang.ClassLoader.loadClass(ClassLoader.java:511)
>                                                                  at java.lang.ClassLoader.loadClass(ClassLoader.java:469)
>                                                                  at com.rits.cloning.ObjenesisInstantiationStrategy.<init>(ObjenesisInstantiationStrategy.java:13) 
>                                                                  at com.rits.cloning.ObjenesisInstantiationStrategy.<clinit>(ObjenesisInstantiationStrategy.java:20) 
>                                                                  at com.rits.cloning.ObjenesisInstantiationStrategy.getInstance(ObjenesisInstantiationStrategy.java:24) 
>                                                                  at com.rits.cloning.Cloner.<init>(Cloner.java:53) 
>                                                                  at com.myproject.project.main$15.onClick(main.java:819) 
>                                                                  at android.view.View.performClick(View.java:4848) 
>                                                                  at android.view.View$PerformClick.run(View.java:20262) 
>                                                                  at android.os.Handler.handleCallback(Handler.java:815) 
>                                                                  at android.os.Handler.dispatchMessage(Handler.java:104) 
>                                                                  at android.os.Looper.loop(Looper.java:194) 
>                                                                  at android.app.ActivityThread.main(ActivityThread.java:5637) 
>                                                                  at java.lang.reflect.Method.invoke(Native Method) 
>                                                                  at java.lang.reflect.Method.invoke(Method.java:372) 
>                                                                  at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:960) 
>                                                                  at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:755) 
>                                                              	Suppressed: java.lang.ClassNotFoundException: org.objenesis.ObjenesisStd
>                                                                  at java.lang.Class.classForName(Native Method)
>                                                                  at java.lang.BootClassLoader.findClass(ClassLoader.java:781)
>                                                                  at java.lang.BootClassLoader.loadClass(ClassLoader.java:841)
>                                                                  at java.lang.ClassLoader.loadClass(ClassLoader.java:504)
>                                                                  		... 16 more
>                                                               Caused by: java.lang.NoClassDefFoundError: Class not found using the boot class loader; no stack available
>

**Comment by kostaskougios** [comment]
objenesis jar is not in your classpath as it seems. If you're using maven it should automatically add transitive dependencies. How do you configure your cp?

**Comment by djdance** [comment]
oh, thanks for naming objenesis jar.

_> How do you configure your cp?_
you didn't describe how to include appropriate string into gradle, so I just downloaded jar library as before.

**Comment by kostaskougios** [comment]
Oh well, I usually use search.maven.org to find artifacts and configs. I.e. see
http://search.maven.org/#artifactdetails%7Cuk.com.robust-it%7Ccloning%7C1.9.5%7Cbundle
Dependency Information / Gradle

I am not using gradle myself but I believe if you include the library like that (and not as a jar), all transitive deps like objenesis will be included as well. 

Closing the issue.
