### ISSUE TITLE
Support partial cloning

### ISSUE THREAD

**Issue by eladh** [kostaskougios/cloning#62]
Hi @kostaskougios .

thanks for this lovely project .

just wanted to ask about supporting a "partial cloning"

in our case we want to clone a complex object graph but only partly based on custom annotation at the class level.

we registered a custom clone object and override the considerImmutable() method but its seems like that the default behavior is to return the default object.

is there any possibility to support some kind of skip functionality , in this case we will exclude the relevant  object graph and set NULL.

best,
elad

**Comment by kostaskougios** [comment]
Hi Elad, so do you mean something like cloner.nullInsteadOfClone() for the annotated classes?

**Comment by eladh** [comment]
Hi @kostaskougios , 

that exactly what i asked for :-)

**Comment by kostaskougios** [comment]
Ok, impl something in 1.9.7

Try something like

Cloner cloner = Cloner.standard();
cloner.registerCloningStrategy(CloningStrategyFactory.annotatedClass(Ann.class, ICloningStrategy.Strategy.NULL_INSTEAD_OF_CLONE));

where Ann.class is your annotation. You can see the impl of CloningStrategyFactory.annotatedClass to create your own if you have to. Ann annotation should annotate any class that you need null'd (inheritance is not taken into account).

**Comment by eladh** [comment]
10x
