### ISSUE TITLE
Support Cloning strategy based on object field and not just object class

### ISSUE THREAD

**Issue by eladh** [kostaskougios/cloning#63]
Hi @kostaskougios  :-)

we got more a scenario were cloning strategy will be decided based on the the field context and not just the class itself

looking at the code : cloneObject got the field context can you also add the field data to the cloneInternal and exposed it as part of the Cloning strategy infrastructure

like this: 

```
 cloner.registerCloningStrategy((field ,toBeCloned )  -> {
           return ICloningStrategy.Strategy.IGNORE;
        });
```

best,
elad

**Comment by kostaskougios** [comment]
Btw notice the IGNORE strategy will ignore the strategy and return a deep clone as if the strategy wasn't present.

**Comment by eladh** [comment]
10x  :-)
