### ISSUE TITLE
Add method to disable/clear all fast cloners?

### ISSUE THREAD

**Issue by emichael** [kostaskougios/cloning#73]
My temporary solution to #72 is to unregister the fast cloners for ArrayList and LinkedList. It would be nice to be able to disable fast cloning altogether (without having to look at the library source and unregister all of the fast cloners that were registered), since they're not *that* much faster and potentially lead to issues.

**Comment by kostaskougios** [comment]
registerFastCloners is protected so that it can be overriden, i.e. do

new Cloner() { override registerFastCloners() { ... NOP or register some fastcloners }}

**Comment by emichael** [comment]
Missed that, thanks!
