### ISSUE TITLE
Illegal Reflective Access

### ISSUE THREAD

**Issue by trexsatya** [kostaskougios/cloning#88]
While using this library I got this log:
`WARNING: An illegal reflective access operation has occurred

WARNING: Illegal reflective access by com.rits.cloning.FastClonerTreeSet (file:/home/satyendra/.gradle/caches/modules-2/files-2.1/io.github.kostaskougios/cloning/1.10.0/153b7d26a2a82909889fb746e6ed9d8f7ae8eabe/cloning-1.10.0.jar) to field java.util.TreeSet.m

WARNING: Please consider reporting this to the maintainers of com.rits.cloning.FastClonerTreeSet

WARNING: Use --illegal-access=warn to enable warnings of further illegal reflective access operations

WARNING: All illegal access operations will be denied in a future release
`

**Comment by BUCKFAE** [comment]
Same issue here.

**Comment by tweimer** [comment]
See #74. @kostaskougios can you close here?

**Comment by kostaskougios** [comment]
please try 1.10.2

**Comment by KenobySky** [comment]
> please try 1.10.2

Maven doesnt have that version yet. What should I do ? 
https://mvnrepository.com/artifact/uk.com.robust-it/cloning


WARNING: An illegal reflective access operation has occurred
WARNING: Illegal reflective access by com.rits.cloning.Cloner (file:/C:/Users/REDACTED/.gradle/caches/modules-2/files-2.1/uk.com.robust-it/cloning/1.9.12/9053df24095825fd54512672b5ee29a2f197b1fa/cloning-1.9.12.jar) to field java.util.TreeSet.m
WARNING: Please consider reporting this to the maintainers of com.rits.cloning.Cloner
WARNING: Use --illegal-access=warn to enable warnings of further illegal reflective access operations
WARNING: All illegal access operations will be denied in a future release

**Comment by tweimer** [comment]
You're using the old artefacts.

Take a look at the readme:
https://search.maven.org/artifact/io.github.kostaskougios/cloning/

And please refer to #74 for further discussion.
