### ISSUE TITLE
why use synchronizedMap?

### ISSUE THREAD

**Issue by doublehero** [kostaskougios/cloning#91]
https://github.com/kostaskougios/cloning/blob/f82a494f0a4e500524394d3cf2723b1038219c01/src/main/java/com/rits/cloning/Cloner.java#L409

we can change synchronizedMap to  ConcurrentHashMap.

**Comment by tweimer** [comment]
It's already fixed in #92 , isn't it?

**Comment by kostaskougios** [comment]
yes the code now is

`private Map<Class, IDeepCloner> cloners = new ConcurrentHashMap<>();`
