### ISSUE TITLE
Custom cloning

### ISSUE THREAD

**Issue by ChristianSchuit** [kostaskougios/cloning#97]
Hi Kostas, 

First off, beautiful work! 

Perhaps it might be good to add to the wiki how to create custom cloner methods. I had one object (XPathExecutable) that stubbornly did not want to be cloned, so I wrapped that in another object, added a `clone()` method and registred (very easily) a custom IFastCloner for it. 

My `clone()` method simply created a new instance with the same properties instead of actually cloning it.

```
public class CustomCloner extends Cloner {

    public CustomCloner() {

        super();
        
        super.registerFastCloner(FlexibleMatcher.class, (t, cloner, clones) -> {

            FlexibleMatcher f = (FlexibleMatcher)t;
            return f.clone();
        });
        
        super.registerFastCloner(FlexibleExtractor.class, (t, cloner, clones) -> {

            FlexibleExtractor f = (FlexibleExtractor)t;
            return f.clone();
        });
    }
}
```

It might help others with the same challenge.

Thanks, Christian

**Comment by kostaskougios** [comment]
Hi Christian, ok regarding the fast cloners but why did you have to "extend Cloner"? The registerFastCloner method is public so you could just instantiate a Cloner instance and then

cloner.registerFastCloner(....)

**Comment by ChristianSchuit** [comment]
Ah, because I am lazy 🤣 By extending the Cloner I can minimize boilerplate code. 

Thanks a lot for your work. Very happy using it!

Sent while on the road. Excuse occasional typos.

**Comment by kostaskougios** [comment]
Ok thanks, I was just wondering if there was something stopping you doing the cloner.registerFastCloner.

I've added an example in the usage page:

https://github.com/kostaskougios/cloning/blob/master/wiki/Usage.md
